Daily_Meal_Planner/Controllers/HomeController.cs
using Daily_Meal_Planner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Diagnostics;

using BusinessLayer;
using DataLayer;
using Operation;

namespace Daily_Meal_Planner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public IProductsRepository _productRepository;

        public HomeController(ILogger<HomeController> logger, IProductsRepository productRepository)
        {
            _logger = logger;
            _productRepository = productRepository;
        }

        public IActionResult Index(string catName)
        {
            // Get all products from the database
            List<Product> products = new List<Product>();
            products = _productRepository.GetAllProducts();

            // Assign the view model
            var vm = new AllProductsViewModel();
            vm.Categories = _productRepository.GetCategoryProducts(products);

            // Get all names of category products
            Prod_Operation operation = new Prod_Operation();
            vm.CategoryList = operation.GetCategoryName(vm.Categories);

            // Get the category name choosen by the user
            vm.CatName = catName;

            return View(vm);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Daily_Meal_Planner/Controllers/MealtimeController.cs
using BusinessLayer;
using Daily_Meal_Planner.Models;
using DataLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Daily_Meal_Planner.Controllers
{
    public class MealtimeController : Controller
    {
        public IUserRepository _userRepository;
        public IMealtimeRepository _mealtimeRepository;

        public MealtimeController(IUserRepository userRepository, IMealtimeRepository mealtimeRepository)
        {
            this._userRepository = userRepository;
            this._mealtimeRepository = mealtimeRepository;
        }

        [Authorize]
        public IActionResult Index(ProductViewModel productViewModel)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("index", "Home");
            }

            foreach(UserMealtime um in _mealtimeRepository.GetUserMealtimes())
            {
                productViewModel.Mealtimes.Add(um.MealtimeName);
            }

            return View(productViewModel);
        }

        public IActionResult SaveUserProduct(ProductAndMealtimeViewModel productAndMealtimeViewModel)
        {
            //List<UserProduct> userProducts = new List<UserProduct>();
            var userProducts = _userRepository.GetAllUserProducts();
            _userRepository.SaveUserProduct(userProducts, productAndMealtimeViewModel.UserNameOrEmail, productAndMealtimeViewModel.MealtimeChoice, productAndMealtimeViewModel.ProductName, productAndMealtimeViewModel.Gramms, productAndMealtimeViewModel.Protein, productAndMealtimeViewModel.Fats, productAndMealtimeViewModel.Carbs, productAndMealtimeViewModel.Calories, productAndMealtimeViewModel.CatName);
            
            return RedirectToAction("index", "Home");
        }
    }
}

Daily_Meal_Planner/Views/Home/Index.cshtml
@model AllProductsViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="Entete text-center">
    @*<div>
        <img src="images\tomatoes-tomatoes-lemon-leaves-garlic-bottle-oil-tree-branches.jpg" alt="" />
    </div>*@
    
    <div><h3 class="title">Dealy Meal Planner</h3></div>
    <div class="spinner-grow text-muted"></div>
    <div class="spinner-grow text-primary"></div>
    <div class="spinner-grow text-success"></div>
    <div class="spinner-grow text-info"></div>
</div>


<div class="body-block03">
    <div class="mealtimeName-block-user"><h5>Category</h5></div>
    <form asp-controller="Home" asp-action="index">
        <div class="Category-block">
            <div>
                <select name="catName" class="form-control bg-white text-warning border-1 border-dark">
                    @if ((Model.CatName == string.Empty || @Model.CatName == null) && Model.CategoryList.Count > 0)
                    {
                        Model.CatName = Model.CategoryList[0];
                    }
                    @if (@Model.CatName == string.Empty || @Model.CatName == null)
                    {
                        @foreach (string name in Model.CategoryList)
                        {
                            <option class="NameStyle">@name</option>
                        }
                    }
                    else
                    {
                        <option>@Model.CatName</option>
                        @foreach (string name in Model.CategoryList)
                        {
                            if (name != Model.CatName)
                            {
                                <option class="NameStyle">@name</option>
                            }
                        }
                    }
                </select>
            </div>
            <div class="justify-content-center">
                <button type="submit" class="btn btn-outline-success mt-3">Search</button>
            </div>
        </div>
    </form>

    
</div>

<div class="body-block02">

<div class="ProdNumber-block">
    <i class="fa-solid fa-universal-access fa-3 orange"></i>
    @{
        int n = 0;
    }
    @foreach (var c in Model.Categories.Where(p => p.Name == Model.CatName).ToList())
    {
        n += c.Products.Count;
    }
    <span class="orange">@n</span>
</div>  

<div class="row">
    <div class="Details col-12">
        
        <div class="row text-center justify-content-center">
            @foreach(var c in Model.Categories)
            {
                @if(c.Name == Model.CatName)
                {
                    @foreach(var p in c.Products)
                    {
                        <div class="Product-block col-sm-4 col-md-3 col-lg-2">
                            @if (p.CategoryName == "Алкоголь")
                            {
                                    <h6 class="NameStyle"><span class="fa-solid fa-wine-bottle fa-shake fa-2x orange"></span> @p.Name</h6>
                            }
                            else
                            {
                                    <h6 class="NameStyle">@p.Name</h6>
                            }
                            <hr />
                            <div class="row justify-content-center">
                                <div class="Product-block01 col-12"><p>Gramms <strong>@p.Gramms g</strong></p></div>
                                <div class="Product-block02 col-sm-6 col-md-6 col-lg-6"><p>Protein <strong>@p.Protein</strong></p></div>
                                <div class="Product-block03 col-sm-6 col-md-6 col-lg-6"><p>Fats <strong>@p.Fats</strong></p></div>
                                <div class="Product-block02 col-sm-6 col-md-6 col-lg-6"><p>Carbs <strong>@p.Carbs</strong></p></div>
                                <div class="Product-block03 col-sm-6 col-md-6 col-lg-6"><p>Calories <strong>@p.Calories</strong></p></div>
                            </div>
                            
                            <form asp-controller="Mealtime" asp-action="index">
                                <button type="submit" class="btn btn-outline-dark mt-3 NameStyle">Add</button>
                                <input type="hidden" name="ProductName" value="@p.Name" />
                                <input type="hidden" name="Gramms" value="@p.Gramms" />
                                <input type="hidden" name="Protein" value="@p.Protein" />
                                <input type="hidden" name="Fats" value="@p.Fats" />
                                <input type="hidden" name="Carbs" value="@p.Carbs" />
                                <input type="hidden" name="Calories" value="@p.Calories" />
                                <input type="hidden" name="CatName" value="@p.CategoryName" />
                                
                            </form>
                        </div>
                    }
                }         
            }
        </div>
    </div>
</div>

<div class="offcanvas offcanvas-start bg-dark" id="demo">
    <div class="offcanvas-header">
        <h3 class="offcanvas-title">Product category</h3>
        <button type="button" class="btn-close text-reset text-light" data-bs-dismiss="offcanvas"></button>
    </div>
    <div class="offcanvas-body">
        <div class="row justify-content-center container01">
            <div class="subContainer col-sm-10 col-md-10 col-lg-10">
                <div class="Category-section text-center col-12">
                    <div><h6>Categories</h6></div>
                    <hr />
                    <div>
                        <ul class="navbar-nav flex-grow-1">
                            @foreach (string name in Model.CategoryList)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-warning subCategory" asp-action="index" asp-route-catName="@name"><h7 class="subCategory">@name</h7></a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Button to open the offcanvas sidebar -->
<div class="btnDownCat">
    <button class="btn btn-dark NameStyle" type="button" data-bs-toggle="offcanvas" data-bs-target="#demo">
        Categories
    </button>
</div>

</div>